namespace OldBit.Spectron.Disassembly.Instructions;

internal static class ExtendedInstructions
{
    internal static Dictionary<int, InstructionTemplate> Index { get; } = new()
    {
        { 0x40, new InstructionTemplate("IN B,(C)") },
        { 0x41, new InstructionTemplate("OUT (C),B") },
        { 0x42, new InstructionTemplate("SBC HL,BC") },
        { 0x43, new InstructionTemplate("LD (<nn>),BC") },
        { 0x44, new InstructionTemplate("NEG") },
        { 0x45, new InstructionTemplate("RETN") },
        { 0x46, new InstructionTemplate("IM 0") },
        { 0x47, new InstructionTemplate("LD I,A") },
        { 0x48, new InstructionTemplate("IN C,(C)") },
        { 0x49, new InstructionTemplate("OUT (C),C") },
        { 0x4A, new InstructionTemplate("ADC HL,BC") },
        { 0x4B, new InstructionTemplate("LD BC,(<nn>)") },
        { 0x4D, new InstructionTemplate("RETI") },
        { 0x4F, new InstructionTemplate("LD R,A") },
        { 0x50, new InstructionTemplate("IN D,(C)") },
        { 0x51, new InstructionTemplate("OUT (C),D") },
        { 0x52, new InstructionTemplate("SBC HL,DE") },
        { 0x53, new InstructionTemplate("LD (<nn>),DE") },
        { 0x56, new InstructionTemplate("IM 1") },
        { 0x57, new InstructionTemplate("LD A,I") },
        { 0x58, new InstructionTemplate("IN E,(C)") },
        { 0x59, new InstructionTemplate("OUT (C),E") },
        { 0x5A, new InstructionTemplate("ADC HL,DE") },
        { 0x5B, new InstructionTemplate("LD DE,(<nn>)") },
        { 0x5E, new InstructionTemplate("IM 2") },
        { 0x5F, new InstructionTemplate("LD A,R") },
        { 0x60, new InstructionTemplate("IN H,(C)") },
        { 0x61, new InstructionTemplate("OUT (C),H") },
        { 0x62, new InstructionTemplate("SBC HL,HL") },
        { 0x63, new InstructionTemplate("LD (<nn>),HL") },
        { 0x67, new InstructionTemplate("RRD") },
        { 0x68, new InstructionTemplate("IN L,(C)") },
        { 0x69, new InstructionTemplate("OUT (C),L") },
        { 0x6A, new InstructionTemplate("ADC HL,HL") },
        { 0x6B, new InstructionTemplate("LD HL,(<nn>)") },
        { 0x6F, new InstructionTemplate("RLD") },
        { 0x70, new InstructionTemplate("IN (C)", IsUndocumented: true) },
        { 0x71, new InstructionTemplate("OUT (C),0", IsUndocumented: true) },
        { 0x72, new InstructionTemplate("SBC HL,SP") },
        { 0x73, new InstructionTemplate("LD (<nn>),SP") },
        { 0x78, new InstructionTemplate("IN A,(C)") },
        { 0x79, new InstructionTemplate("OUT (C),A") },
        { 0x7A, new InstructionTemplate("ADC HL,SP") },
        { 0x7B, new InstructionTemplate("LD SP,(<nn>)") },
        { 0xA0, new InstructionTemplate("LDI") },
        { 0xA1, new InstructionTemplate("CPI") },
        { 0xA2, new InstructionTemplate("INI") },
        { 0xA3, new InstructionTemplate("OUTI") },
        { 0xA8, new InstructionTemplate("LDD") },
        { 0xA9, new InstructionTemplate("CPD") },
        { 0xAA, new InstructionTemplate("IND") },
        { 0xAB, new InstructionTemplate("OUTD") },
        { 0xB0, new InstructionTemplate("LDIR") },
        { 0xB1, new InstructionTemplate("CPIR") },
        { 0xB2, new InstructionTemplate("INIR") },
        { 0xB3, new InstructionTemplate("OTIR") },
        { 0xB8, new InstructionTemplate("LDDR") },
        { 0xB9, new InstructionTemplate("CPDR") },
        { 0xBA, new InstructionTemplate("INDR") },
        { 0xBB, new InstructionTemplate("OTDR") },

    };
}